name: Build and Deploy

on:
  push:
    branches:
      - master
  workflow_dispatch:
  
env:
  CI: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install --force

      - name: Build Project
        run: npm run build

      - name: Copy File to Web Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_KEY }}
          source: "build/*"
          target: "/home/axra/"

      - name: SSH into Server and Run Script
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_KEY }}
          port: 22
          script: |
            echo ${{secrets.SERVER_PASSWORD}} | sudo -S ./dashboard_automate.sh
     
          
            
